# Site settings
title: 
header-img: img/home-bg.png
email: romeogono1@aol.com
copyright_name: Arbeker01
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Arbeker01
learn_profile: Arbeker01
email_username: romeogono1@aol.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
